
alertmanager:
  config:
    route:
      receiver: 'prometheus-msteams'
    receivers:
      - name: "null"
      - name: 'prometheus-msteams'
        webhook_configs:
        - url: 'http://prometheus-msteams:2000/teams'
          send_resolved: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.dev.example.com
    annotations:
      kubernetes.io/ingress.class: "nginx"


grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.dev.example.com
    annotations:
      kubernetes.io/ingress.class: "nginx"

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.dev.example.com
    annotations:
      kubernetes.io/ingress.class: "nginx"
