apiVersion: v1
appVersion: v1.4.2
description: A Helm chart for Kubernetes
home: https://github.com/prometheus-msteams/prometheus-msteams
maintainers:
- name: bzon
  url: https://github.com/bzon
- name: Knappek
  url: https://github.com/Knappek
name: prometheus-msteams
version: 1.1.1
